language: node_js

install:
  - npm ci

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npx audit-ci --low --config audit-ci.json
  - npm run test
  - npx eslint src
  - npm run dist

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
  slack:
    secure: RYs94hJL+5tdcWEZKkDDX2eR50rwiv5ZEfzrCci2HUKS1UGCsv7k81/6tw4WBpCYR7pPclMVbIDm0pCZ9UaWXXlexTmXwApV6Wt6G7H+ZRlnH16BPkzdczs0/4mKB1lx1/ql5hq5GCcuFUdrmk89c6Yi6/3jm4ivVKVMekJe32FPamb4JjBZlJIFGwOMxCLX+8JRABY3d7R+kbmjaab2DCafAntwtQwH77K99wBV7yWh42ra9xaaqmhqqtL/qbYJ+H7K0YNXswqvNvqLpbA2PdsrIEQpGBnLvFThaLwdcI9hCQdf73qLVANAulcKYoJnUFOCCtP6rXTWT2BifCIGr5ndkZJwS3cFlOmAZWBvJBv9ic5TA0cMPpK4HFr7U9TMHYydwaXfOzu2SahHMZKXu5TmZgtVfolvUDtFP7CzwqXJoRa294rrLlXMhZxmH1F99+5maprLduIEyTEFA7ZkbEanEY/Iojd1IYXXAifmm0AH1gJxP1NPYUYcE8OGOTJj0+qr3ug9zcNy3Hwk2xZfZnyfo3uzFM1RpnaBDALKgSXZEAYGAmy/YsvwZsHowZJbr9MjvrBUuuAzkjBbTGKudXaoxz0C49fiYhpV/SoywZxKClKx7UQzeZbgH+zL35VCQcEneY4+/JRn0cJcXoxzlxeleQomIXWW1SEKvQkQy+o=
