---
name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        cache: 'npm'
    - run: npm ci --prefer-offline --no-audit
    - run: npm run build
    - run: npm test
    - run: npx eslint src
    - run: npm run dist
